config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  get '/lists/new', to: 'lists#new', as: :new_list
  post '/lists', to: 'lists#create'
  get '/lists/:id', to: 'lists#show', as: :list
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  validates :comment, length: { minimum: 6 }
  validates :movie_id, uniqueness: { scope: :list_id }

  belongs_to :movie
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks

  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true, presence: true
  validates :overview, presence: true

  has_many :bookmarks
  has_many :lists, through: :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @movies = @list.movies
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to @list, notice: 'List successfully created.'
    else
      render :new
    end
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="content-wrapper">
      <%= yield %>
    </div>
    </div>
    <div class="footer">
    </div>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<div class="banner">
  <h1>Your lists</h1>
  <%= link_to "+ New list", new_list_path, class: "btn-ghost" %>
</div>
<div class='container'>
<div class="add-new">
    </div>
    <div class='cards'>
    <% @lists.each do |list| %>
      <div class='card-list'><%=link_to list.name, list_path(list), class: 'list'%></div>
    <%end%>
    </div>
</div>

app/views/lists/new.html.erb
<div class="banner">
  <h1>New list</h1>
  <%= link_to "Back to your lists", root_path, class: "btn-ghost" %>
</div>
<div class="form"></div>
  <%= simple_form_for(@list) do |f| %>
    <%= f.input :name %>
    <%= f.input :photo, as: :file %>
    <%= f.submit %>
  <% end %>
</div>

app/views/lists/show.html.erb
<div class="banner">
  <h1><%= @list.name %></h1>
  <%= link_to "Back to your lists", root_path, class: "btn-ghost" %>
</div>

<div class='container'>
  <% @movies.each do |movie| %>
    <div class="card-movie">
      <%= image_tag movie.poster_url, alt: "Movie Poster should be here" %>
      <div class="card-movie-infos">
        <h2><%= movie.title %></h2>
        <p><%= movie.overview %></p>
        <p>Rating : <%= movie.rating %></p>
      </div>
    </div>
  <% end %>
</div>